'use client';
import {useState} from 'react';
import {ArrowRight, Bitcoin, Building2, Coins, LineChart, Pickaxe, Landmark, ShieldCheck, WalletCards, Sparkles, Menu, X, ChevronRight, Bot, CreditCard, Bell, Lock, BarChart3} from 'lucide-react';

const products=[
['Cryptocurrency','Crypto investment programs with published terms and risk disclosures.',Bitcoin],
['Real Estate','Property-focused opportunities with documented income and ownership structures.',Building2],
['Gold','Gold-linked allocations with transparent unit and valuation reporting.',Coins],
['Stocks','Managed market portfolios and diversified baskets.',LineChart],
['Copy Trading','Follow disclosed strategies with performance and risk metrics.',Sparkles],
['Mining','Mining/hashpower programs with contract terms and operating disclosures.',Pickaxe],
['Loans & Banking','Account and lending services subject to eligibility and applicable regulation.',Landmark],
];
const plans=[
['Digital Asset Growth','Crypto','Variable','€250+'],['Property Income Pool','Real Estate','Variable','€1,000+'],['Gold Allocation','Gold','Variable','€500+'],['Market Portfolio','Stocks','Variable','€500+'],['Mining Contract','Mining','Contract-based','€250+'],['Copy Strategy','Copy Trading','Variable','€250+']
];

export default function Home(){
 const [demo,setDemo]=useState(false),[mobile,setMobile]=useState(false);
 return <main>
 <header className="topbar"><div className="navwrap"><Brand/><nav className="desktopNav"><a href="#products">Products</a><a href="#plans">Plans</a><a href="#how">How it works</a><a href="#security">Security</a><a href="#faq">FAQ</a></nav><div className="navActions"><button className="btn btn-secondary desktopOnly" onClick={()=>setDemo(true)}>Open demo</button><a className="btn btn-primary" href="#plans">View plans <ArrowRight size={16}/></a><button className="iconBtn mobileOnly" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></div>{mobile&&<div className="mobileNav"><a href="#products" onClick={()=>setMobile(false)}>Products</a><a href="#plans" onClick={()=>setMobile(false)}>Plans</a><a href="#how" onClick={()=>setMobile(false)}>How it works</a><a href="#security" onClick={()=>setMobile(false)}>Security</a><button className="btn btn-secondary" onClick={()=>{setDemo(true);setMobile(false)}}>Open demo</button></div>}</header>
 <section className="section hero gridbg fade"><div className="heroCopy"><span className="pill">Premium multi-asset investment ecosystem</span><h1>Premium multi-asset investment programs with <span className="gold">structured</span> daily profit crediting.</h1><p className="lead">Crypto, real estate, gold, stocks, mining, copy trading and account services—managed in one smart dashboard with clear terms, activity records and risk disclosures.</p><div className="heroBtns"><a className="btn btn-primary" href="#plans">Start Investing <ArrowRight size={17}/></a><a className="btn btn-secondary" href="#plans">View Plans</a><button className="textBtn" onClick={()=>setDemo(true)}>Explore dashboard <ChevronRight size={16}/></button></div></div><div className="heroPanel glass"><div className="panelTop"><span className="pill">Live platform preview</span><span className="dot">●</span></div><div className="heroBalance">€—</div><div className="muted small">Account balance · Connect production ledger</div><div className="miniChart"><span/><span/><span/><span/><span/><span/><span/><span/><span/><span/></div><div className="heroStats"><Stat label="Active investments" value="—"/><Stat label="Profit credits" value="—"/><Stat label="Withdrawal" value="—"/></div></div></section>
 <section id="products" className="section"><div className="sectionHead"><div><span className="pill">One platform</span><h2>Multi-asset access</h2></div><span className="muted small">Availability and eligibility vary by jurisdiction</span></div><div className="productGrid">{products.map(([n,d,I])=><div className="glass card product" key={n as string}><I className="cyan" size={25}/><h3>{n as string}</h3><p className="muted">{d as string}</p><ChevronRight className="muted" size={17}/></div>)}</div></section>
 <section id="plans" className="section alt"><span className="pill">Plans & products</span><h2>Structured programs</h2><p className="muted maxText">Each production plan must be backed by approved legal terms, disclosed risks, eligibility rules and applicable authorization before customers can transact.</p><div className="planGrid">{plans.map(p=><div className="glass card plan" key={p[0]}><span className="pill">{p[1]}</span><h3>{p[0]}</h3><div className="rows"><div><span>Structure</span><b>{p[2]}</b></div><div><span>Minimum</span><b>{p[3]}</b></div><div><span>Crediting</span><b>According to terms</b></div></div><a href="/terms" className="btn btn-secondary full">View terms</a></div>)}</div></section>
 <section id="how" className="section"><span className="pill">How it works</span><h2>A clear path from account to reporting</h2><div className="steps">{['Create account & verify','Fund an eligible wallet','Select an approved program','Track activity & withdrawals'].map((x,i)=><div className="glass card step" key={x}><div className="stepNum">0{i+1}</div><h3>{x}</h3><p className="muted">Every supported action is recorded in the account activity ledger.</p></div>)}</div></section>
 <section id="security" className="section"><div className="glass security"><div><span className="pill"><ShieldCheck size={13}/> Security by design</span><h2>Auditable infrastructure and role-based controls.</h2><p className="muted lead2">Authentication, wallet balances, transaction records, administrative actions and notifications are separated into controlled services with audit trails.</p></div><div className="securityGrid"><Mini icon={<Lock/>} title="2FA" text="Account protection"/><Mini icon={<ShieldCheck/>} title="RBAC" text="Admin permissions"/><Mini icon={<BarChart3/>} title="Audit" text="Transaction history"/><Mini icon={<Bell/>} title="Alerts" text="Real-time notices"/></div></div></section>
 <section className="section"><div className="featureGrid"><Feature icon={<WalletCards/>} title="Six-wallet architecture" text="Main, Profit, Bonus, Withdrawal, Deposit and Payment wallets with transaction history."/><Feature icon={<CreditCard/>} title="Payments & cards" text="Production-ready integration points for cards, bank transfer and approved digital-asset rails."/><Feature icon={<Bot/>} title="AI assistant" text="A configurable help assistant for wallets, plans, tutorials and frequently asked questions."/></div></section>
 <footer id="faq" className="footer"><div className="footerGrid"><div><Brand/><p className="muted small">Premium investment technology platform.</p></div><div><b>Platform</b><a href="#products">Products</a><a href="#plans">Plans</a><a href="#security">Security</a></div><div><b>Resources</b><a href="#how">How it works</a><a href="#faq">FAQ</a><a href="/dashboard">Dashboard</a></div><div><b>Important</b><p className="muted small">Demo figures and simulated activity are not real customer balances. Returns are not guaranteed. Replace all placeholders with verified company, legal, regulatory and product information before accepting customers.</p></div></div></footer>
 {demo&&<Demo close={()=>setDemo(false)}/>}</main>
}
function Brand(){return <div className="brand"><div className="logo">SP</div><div><div className="brandName">Savix<span>Prime</span></div><div className="eyebrow">MULTI-ASSET PLATFORM</div></div></div>}
function Stat({label,value}:{label:string,value:string}){return <div><div className="muted tiny">{label}</div><strong>{value}</strong></div>}
function Mini({icon,title,text}:{icon:any,title:string,text:string}){return <div className="glass mini"><div className="cyan">{icon}</div><b>{title}</b><span className="muted small">{text}</span></div>}
function Feature({icon,title,text}:{icon:any,title:string,text:string}){return <div className="glass card feature"><div className="featureIcon cyan">{icon}</div><h3>{title}</h3><p className="muted">{text}</p></div>}
function Demo({close}:{close:()=>void}){return <div className="modal"><div className="modalBox glass"><div className="modalHead"><div><span className="pill">DEMO ENVIRONMENT</span><h2>SavixPrime Dashboard</h2></div><button className="iconBtn" onClick={close}><X/></button></div><div className="walletGrid"><Wallet name="Main Wallet" value="€25,000.00"/><Wallet name="Profit Wallet" value="€1,240.00"/><Wallet name="Bonus Wallet" value="€380.00"/><Wallet name="Withdrawal Wallet" value="€650.00"/><Wallet name="Deposit Wallet" value="€4,000.00"/><Wallet name="Payment Wallet" value="€120.00"/></div><div className="glass activity"><div className="panelTop"><b>Live investments</b><span className="pill">Simulated</span></div><div className="activityRow"><span>Digital Asset Growth</span><span>+€18.42</span><span className="cyan">Next credit: simulated</span></div><div className="activityRow"><span>Property Income Pool</span><span>+€7.10</span><span className="cyan">Next credit: simulated</span></div><p className="muted small">All values in this demo are fictitious and do not represent customer funds or actual investment performance.</p></div></div></div>}
function Wallet({name,value}:{name:string,value:string}){return <div className="glass card"><span className="muted small">{name}</span><div className="walletValue">{value}</div><div className="walletActions"><button>Deposit</button><button>Withdraw</button><button>Transfer</button></div></div>}
