'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, ShieldCheck } from 'lucide-react';
import { supabaseBrowser } from '../../lib/supabase';

export default function Register(){const [name,setName]=useState('');const [email,setEmail]=useState('');const [country,setCountry]=useState('');const [password,setPassword]=useState('');const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);
async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');try{const sb=supabaseBrowser();const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:name,country}}});if(error)throw error;if(data.session){window.location.href='/dashboard';return;}setMsg('Account registration submitted. Check your email for the confirmation link, then sign in.');}catch(err){setMsg(err instanceof Error?err.message:'Registration failed. Check your Supabase settings.');}finally{setBusy(false);}}
return <main className="authPage"><div className="authCard glass"><div className="brand"><div className="logo">SP</div><div><div className="brandName">Savix<span>Prime</span></div><div className="eyebrow">CREATE ACCOUNT</div></div></div><h1>Open an account</h1><p className="muted">Create your account. Identity verification and financial eligibility checks must be completed separately before any regulated service is offered.</p><form onSubmit={submit}><label>Full name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" autoComplete="name"/></label><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email"/></label><label>Country<input required value={country} onChange={e=>setCountry(e.target.value)} placeholder="Country of residence" autoComplete="country-name"/></label><label>Password<input type="password" required minLength={10} value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 10 characters" autoComplete="new-password"/></label><button className="btn btn-primary full" disabled={busy} type="submit">{busy?'Creating account…':'Create account'} <ArrowRight size={16}/></button></form>{msg&&<div className="notice" role="status">{msg}</div>}<p className="muted small">Already registered? <Link href="/login">Sign in</Link></p><div className="secure"><ShieldCheck size={18}/><span>Registration uses Supabase Auth. No deposit is collected and no investment is created during signup.</span></div><a className="back" href="/">← Back to SavixPrime</a></div></main>}
