'use client';
import { useEffect, useState } from 'react';
import { WalletCards, Bell, Bot, CreditCard, ArrowUpRight, ArrowDownLeft, Menu, X, Home, PieChart, Settings, LogOut, RefreshCw } from 'lucide-react';
import { supabaseBrowser } from '../../lib/supabase';

type Wallet={id:string;type:string;currency:string;balance:string|number};
type Tx={id:string;type:string;amount:string|number;currency:string;status:string;created_at:string};
const labels:Record<string,string>={main:'Main Wallet',profit:'Profit Wallet',bonus:'Bonus / Rewards',withdrawal:'Withdrawal Wallet',deposit:'Deposit Wallet',payment:'Payment Wallet'};
const order=['main','profit','bonus','withdrawal','deposit','payment'];
export default function Dashboard(){const [open,setOpen]=useState(false);const [email,setEmail]=useState('');const [wallets,setWallets]=useState<Wallet[]>([]);const [txs,setTxs]=useState<Tx[]>([]);const [msg,setMsg]=useState('Loading your secure account…');const [loading,setLoading]=useState(true);
async function load(){setLoading(true);try{const sb=supabaseBrowser();const {data:{user},error:authErr}=await sb.auth.getUser();if(authErr||!user){window.location.href='/login';return;}setEmail(user.email||'');const [w,t]=await Promise.all([sb.from('wallets').select('id,type,currency,balance').eq('user_id',user.id),sb.from('transactions').select('id,type,amount,currency,status,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(12)]);if(w.error)throw w.error;if(t.error)throw t.error;setWallets(w.data||[]);setTxs(t.data||[]);setMsg((w.data||[]).length?'Your balances are loaded from your account ledger.':'Your account is ready. Wallet records will appear after the database setup is completed.');}catch(e){setMsg(e instanceof Error?e.message:'Could not load account data. Check your Supabase setup.');}finally{setLoading(false);}}
useEffect(()=>{load();},[]);
async function logout(){const sb=supabaseBrowser();await sb.auth.signOut();window.location.href='/login';}
const money=(v:string|number,c:string)=>new Intl.NumberFormat(undefined,{style:'currency',currency:c||'EUR',maximumFractionDigits:2}).format(Number(v||0));
return <main className="dash"><aside className={open?'side open':'side'}><div className="sideBrand">SP <span>SavixPrime</span></div>{[['Overview',Home],['Investments',PieChart],['Wallets',WalletCards],['Notifications',Bell],['AI Assistant',Bot],['Settings',Settings]].map(([n,I])=><a key={n as string} href={n==='Overview'?'#overview':'#activity'}><I size={17}/>{n as string}</a>)}<button className="logout" onClick={logout}><LogOut size={17}/>Sign out</button></aside><div className="dashMain" id="overview"><header className="dashHead"><button className="iconBtn mobileOnly" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div><div className="muted small">Account overview</div><h1>Welcome{email?`, ${email}`:''}</h1></div><div className="dashRight"><button className="iconBtn" onClick={load} aria-label="Refresh account"><RefreshCw size={18}/></button><div className="avatar">SP</div></div></header><div className="notice"><Bell size={17}/><span>{msg}</span></div><section className="walletGrid">{order.map(type=>{const w=wallets.find(x=>x.type===type);return <div className="glass card" key={type}><span className="muted small">{labels[type]}</span><div className="walletValue">{w?money(w.balance,w.currency):'—'}</div><div className="walletActions"><button disabled><ArrowDownLeft/>Deposit</button><button disabled><ArrowUpRight/>Withdraw</button></div></div>})}</section><section className="dashGrid" id="activity"><div className="glass card"><div className="panelTop"><div><span className="pill">Account ledger</span><h2>Recent transactions</h2></div><span className="muted small">{loading?'Loading…':'Latest 12'}</span></div>{txs.length?<div className="investments">{txs.map(t=><div className="invest" key={t.id}><div><b>{t.type.replaceAll('_',' ')}</b><span className="muted small">{new Date(t.created_at).toLocaleString()}</span></div><div><b>{money(t.amount,t.currency)}</b><span className="muted small">{t.status}</span></div></div>)}</div>:<p className="muted">No transaction records yet. This page displays database records only; it does not simulate deposits, withdrawals, or profits.</p>}</div><div className="glass card"><span className="pill">Account services</span><div className="quick"><button disabled><WalletCards/>Manage wallets</button><button disabled><CreditCard/>Payment methods</button><button disabled><Bot/>Help assistant</button><button disabled><Bell/>Notifications</button></div><p className="muted small">Payment and investment actions remain disabled until compliant, verified provider integrations are configured.</p></div></section></div></main>}
